# A Stock Screener Configuration
paths:
  base_dir: '/Users/mickyli/Downloads/UGit'
  data_dir: 'Astocksdata'
  backup_dir: '/Users/mickyli/Documents/output'

akshare:
  batch_size: 299
  batch_delay: 3
  start_date: '20240901'

screening:
  cvd_period: 14              # CVD计算周期
  udvr_period: 14             # UDVR计算周期
  udvr_thresholds: [9, 8, 7, 6]   # UDVR筛选阈值

stock_prefixes:               # 股票代码前缀过滤
  - '00'
  - '30'
  - '60'
  - '68'
