# A Stock Screener Configuration
paths:
  base_dir: '.'
  data_dir: 'Astocksdata'
  backup_dir: 'outputA'

akshare:
  batch_size: 299
  batch_delay: 3
  start_date: '20240901'

screening:
  cvd_period: 14
  udvr_period: 14
  udvr_thresholds: [9, 8, 7, 6]

stock_prefixes:
  - '00'
  - '30'
  - '60'
  - '68'
